### PR TITLE
Web update

### PR DESCRIPTION
**Pull request by zignig**
Another web viewer update.  This is a backport of the current cqparts-server viewer. 

Pressing space hides parts and "A" shows them all , the autorotate is also a button.

### CODE REVIEW

**Comment by fragmuffin** [comment]
Nice work @zignig !

**Screenshot**
screenshot

**Comment by fragmuffin** [comment]
I think that's great! :shipit: 

A word of warning though... I see this web-display as either:
- a temporary measure until the `cadquery` GUI becomes the standard, or
- an intentionally simple display that will (in future) have a link to the `cadquery` GUI.
  a "for a better experience click here" sort of thing.

I just say that because, if you were considering doing an overhaul, it may not be worth it.
`cqparts-server` on the other hand, *is* worth making awesome ;), especially if you have plans on porting its functionality to `cadquery-gui` when it gets momentum.

**Comment by zignig** [comment]
> A word of warning though... I see this web-display as either:

I see the web-display as "I don't have any __awesome__ editor installed" fallback. The back port only took 10 minutes to do and I will work towards making the "cqparts-viewer" web object  a drop in backport  with no edits.

The cqparts-server is coming along but it has some crinkly edges as my dev time is swapping between making cqparts objects and developing the display.

My biggest frustration at the moment is  swapping between python<-->golang<-->javascript and having my fingers munt the syntax. ;)

**Comment by zignig** [comment]
Also... 

need to push the gltf export code  into cadquery (@dcowden) to have a single display interface. I will also make the cqpartsViewer.js into web-component (https://developer.mozilla.org/en-US/docs/Web/Web_Components) for usage in the documentation so we can get rid of the icky iFrames.

**Comment by jmwright** [comment]
> cqparts-server on the other hand, is worth making awesome ;), especially if you have plans on porting its functionality to cadquery-gui when it gets momentum.

I think that as a community we need to have a discussion about cadquery-gui vs cqparts-server and where to put our efforts. I think this is especially relevant with Adam's launch of CQ-editor. cadquery-gui is a stand-alone GUI (that could be run as a web app) built using Electron and Javascript. I haven't been able to get CQ-editor running quite yet, but the debugging and inspection features alone put it light years ahead of cadquery-gui. Running as a web app, cadquery-gui pulls a lot of baggage along with it because of Electron. cqparts-server is simpler and lighter, and enables a very different workflow from CQ-editor, which I think is important. That more modular workflow is one that I think a good number of CQ/cqparts developers will favor.

So my question is this: Should we favor cqparts-server (or some other similar solution) over cadquery-gui, which (very likely) won't be our best option for a stand-alone GUI, and is less than optimal for a web based workflow? Assuming that @zignig is willing to take contributions to cqparts-server, I'd rather put my effort there than in something (cadquery-gui) that kind of duplicates what CQ-editor will do better. I'd also rather put my efforts into helping with CQ-editor than in continuing to push cadquery-gui. I'm a big fan of trying things and letting the best ideas survive, and I feel like we're at a point where we may be able to start focusing on 2 official options (CQ-editor and cqparts-server) going forward. I think that both the FreeCAD module and the Jupyter Notebook integration will continue to be relevant, but will be used by smaller subsets of the community once CQ-editor and cqparts-server become mainstream.

Thoughts?

Tagging @dcowden @adam-urbanczyk and @RustyVermeer as well.

**Comment by dcowden** [comment]
I'm reserving judgement till i try Adam's new GUI firsthand ...

**Comment by fragmuffin** [comment]
> need to push the gltf export code into cadquery

@zignig I've been thinking that for a while... see #49 
Actually, I should do that soon so there's an overlap of the exporter being functional in both `cadquery` & `cqparts` for a while.

**Pull request merged**
