### PR TITLE
TravisCI

### PR DESCRIPTION
**Pull request by fragmuffin**

### CODE REVIEW

**Comment by fragmuffin** [comment]
It appears the `ubuntu-py2` branch is experiencing this issue: pypa/pip#5240.
I can replicate the issue on my machine, I just didn't see it before because my `ubuntu:16.04` image was 5 months old.

**Comment by fragmuffin** [comment]
The TravisCI checks seem to be working, but it's quite temperamental.

I've had to re-run the jobs a few times, with differing results.
It might be worth putting a few checks into the docker build scripts to make debugging the false fails a bit easier, but that (should be) out of scope for this change.

False fails aren't damaging; the more information we get, the easier it will be to find the problems... so I'm merging this in.

Phew!... I genuinely thought this would be a quick and easy job... live and learn :stuck_out_tongue_winking_eye: 
The lesson: nothing is ever easy :neutral_face:

**Comment by jmwright** [comment]
@fragmuffin There are false fails with the CadQuery Travis CI system too. It usually has to do with the download of a package timing out.

**Comment by fragmuffin** [comment]
@jmwright that makes sense.

This TravisCI setup is very simple, split into 3 steps:
1. build base docker container
1. build test-specific docker container (from base)
1. run tests inside container

This whole process could be sped up a lot, and reduce the load on Travis by periodically building the test-specific docker container, and uploading it to docker's system.... then the _build_ process would be replaced with a simple download of the image.

**Pull request merged**
