### PR TITLE
Localize web interface

### PR DESCRIPTION
**Pull request by zignig**
Clean up web interface to use local js files and not CDN.

changes material basis to work with vanilla three js #80 

make the web server listen on network address for remote access.

### CODE REVIEW

**Comment by gntech** [comment]
Really nice work! :)

I have some ideas/suggestions:

What do you think about making autorotate optional? Perhaps something like:

``` python
from cqparts.display import web_display

web_display(thing, autorotate=True) # defaults to False if not specified
```

Also, it would be really nice if we would be able to add some smartness to the initial camera placement based on the size of the object. I tested initially with a box(1,1,1) and it was so small in the webview that I thought something went wrong because I did not see it. The same would be true for very large objects.

I am not sure exactly how the logic for that should work but perhaps a starting point could be the bounding box of the model that is displayed? What do you think, perhaps it could be added as a feature later

**Comment by zignig** [comment]
@fragmuffin  has actually written some placement code , I have just failed to add it in.

@fragmuffin please don't merge this yet I will get camera placement going first.

The bounding box calculation and a heuristic to place the camera is done inside cqparts and then pushed  out to the web interface via templating. 

I am also working on a golang web proxy that will run the python script every time the file is saved and push the model to the web interface automagically. For now I'll just clean up the display() / web_display().

**Comment by jmwright** [comment]
I'm probably too late on this, but there's some [code](https://github.com/jmwright/cadquery-gui/blob/master/assets/js/viewer.js#L148) in the stand-alone CadQuery GUI that figures out how far out to move the camera.

**Comment by zignig** [comment]
@jmwright it was already in the code , I didn't template it properly.

Fixed with latest commit.

**Comment by zignig** [comment]
That said , we should avoid duplication between cadquery and cqparts.

**Comment by fragmuffin** [comment]
> What do you think about making autorotate optional?

Good suggestion @gntech, and perhaps a rotational velocity parameter as well.

> @fragmuffin has actually written some placement code , I have just failed to add it in.

@zignig I think there's something wrong with that code, I've noticed that sometimes the camera, or the object isn't placed centrally... anyway, that's out of scope of this PR.

> @fragmuffin please don't merge this yet I will get camera placement going first.

No problem @zignig , you let me know when you're ready.
I'm just happy to have contributors! :blush:

**Comment by fragmuffin** [comment]
Oh!, and I totally forgot to say: very nice work @zignig :heart:

**Comment by zignig** [comment]
Autorotate can now be passed to display , defaults to off

display(AwesomeThing,autorotate=True)

**Comment by fragmuffin** [comment]
@zignig FYI: I'm changing how display environments work, but they're very easily ported, so it's not a big issue.

**Comment by zignig** [comment]
Have added a new mode into display.  By using https://github.com/zignig/cqparts-server it monitors a file ( soon to be a folder )  for changes and runs and renders it. 

Also has the feature (accidental :) ) that if you run any cqparts file that calls display(Parts) it will update in the web interface.

Has made my part development speed with a Vim terminal and a web browser significantly faster.

**Comment by zignig** [comment]
@fragmuffin  shall we merge this here and when you change the display code i can update the cqpss to the new structure?

Going forward i would like to make this viewer the one that the sphinx doc uses. Simple interface no frills.

**Comment by fragmuffin** [comment]
@zignig Yes, I'd love to, I just want to test it out.
I can't today, I've got to get some sleep, but I definitely want to try it out on the weekend.

**Comment by fragmuffin** [comment]
FYI: I've started #94, but I'll merge this one in first, and migrate it to inherit from `DisplayEnvironment`

**Comment by fragmuffin** [comment]
@zignig I've made some changes.

I hope you don't mind, but I changed how the primary function does it's job (see: https://github.com/fragmuffin/cqparts/pull/89/commits/937e412e59a4efcb55a039eae02787715893b7a5)

But I've just realized I've broken an assumption between the server and the display method... [fixing]...

**Comment by fragmuffin** [comment]
@zignig I haven't tested this with your `cqparts-server`, but the requirements of the `cqpss` method is straight forward, and easy to test.

I've got 2 questions with the temporary file storage for the exported content.
Relating to lessons learnt by `tempfile` in their [`mkdtemp()`](https://docs.python.org/2/library/tempfile.html#tempfile.mkdtemp) implementation:
- **security**: folder is created and viewable by all users on the host OS
- **persistence**: folder is created, and populated, but not removed.

One method to solve this could be to use `tempfile` to:
- create a new secure temporary directory with a `cqpss_` prefix each time, and pass the folder's location in the `post` request.
- get `cqparts-server` to remove any temporary `cqpss_*` folders on startup.

I don't think this is too critical, so if you decide I'd also be happy to merge it in, and create an issue.

**Comment by zignig** [comment]
@fragmuffin the cqparts-server is still in flux but I have to rationalise the way the files are accessed / stored.

For now I think we merge,  make an issue and I will do some reading and consider a secure methodology to transfer the generated files between cqparts and the server.

Thanks for your comprehensive reviews of my scrappy code ;)

**Comment by fragmuffin** [comment]
Sounds good to me @zignig.

I also tested your `autorotate` feature... very nice :+1: 

> Thanks for your comprehensive reviews of my scrappy code ;)

No problem! But it's less your code style, and more my possessiveness of `cqparts` ;)
There's a style across the whole library that I'd like to keep, mostly PEP8 flavoured.

I'll merge this in and pull it in to #94

**Comment by fragmuffin** [comment]
Thanks for your contribution @zignig ! :medal_sports:

**Comment by fragmuffin** [comment]
@zignig as discussed, I've created #100 to track cqparts server export security & storage maintenance.

**Pull request merged**
